spring.datasource.url=jdbc:mysql://kodama.proxy.rlwy.net:30206/railway?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=tJAkLZDfjAKrvnUftZuEzMWmpWJuANPp

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true